### ISSUE TITLE
Database Weirdness

### ISSUE THREAD

**Issue by dustinmichels** [carleton-cs-energy-analytics/energy-analytics-comps#49]
Making note of some odd stuff we should probably resolve. When I call `api.buildings()` in Python I get:

- 'Hulings' & Hulings Hall',
    * (Hulings has many points, Hulings Hall just has steam/gas/electricity)
- 'Evans', & 'Evans Hall',
- 'Cassat Hall', & 'Cassat Hall/James Hall',
    * (calling `api.building('Cassat Hall/James Hall')` causes Value error 😢 )
- 'Goodhue' & 'Goodhue Hall'
    * 'Goodhue' has electricity data, but 'Goodhue Hall' has steam and gas 😮  
- 'James' & 'James Hall'
    * 'James' has electricity, 'James Hall' has solar
- Two 'Leighton Hall' entries
    * The first has electricity, the second has steam
- Two 'Olin Hall'
    * The first has electricity, steam, and water; the second has steam condensate
- 'Rec' and 'Recreation Center'
    * Rec has more points

*Note:* You can explore this data interactively using [this jupyter notebook](https://github.com/carleton-cs-energy-analytics/marthas-dashboard/blob/room-inspector/marthas_dashboard/data%20tool.ipynb), if you have ipywidgets installed!

**Comment by jacklightbody** [comment]
Discussed at https://carlcs-analytics.slack.com/archives/C6ZSHFW49/p1516930280000142 not sure if that is still happening/is a priority. We could probably write some sql statement to merge the two, though that would be a bit jury rigged
